### ISSUE TITLE
Please add link to published app to project's URL (and README)

### ISSUE THREAD

**Issue by filiph** [isoos/gwt_mail_sample#4]
https://isoos.github.io/gwt_mail_sample/

This should be featured prominently.

**Comment by filiph** [comment]
Also, link to the original medium post from the README

**Comment by filiph** [comment]
Please also add the link to the deployed demo here (to the right of the description):

![screen shot 2017-05-04 at 10 22 02](https://cloud.githubusercontent.com/assets/919717/25716331/8e18114e-30b3-11e7-8454-973437466af6.png)

**Comment by isoos** [comment]
Ah, yeah, done.
